name: Dev build and publish Docker distributions to Github Container Registry ghcr.io
on:
  push:
    branches-ignore:
      #- master
      - version-*
  workflow_dispatch:
    inputs:
      ownerName:
        description: "ownerName"
        default: "ak49630"
        type: string
      javaVersion:
        required: false
        type: string
        default: '11' 
      
env:
  OWNER_REPO: "${{ github.repository_owner }}"
jobs:
 
  build-job:
    #uses: $OWNER_REPO/.github/.github/workflows/trivy-tpl.yml@main
    uses: ak49630/.github/.github/workflows/trivy-tpl.yml@main
    secrets:
      CR_PAT: ${{ secrets.CR_PAT }}

#  build-job-relative-path:
#    uses: "${{ github.repository_owner }}"/.github/.github/workflows/trivy-tpl.yml@main
#    secrets:
#      CR_PAT: ${{ secrets.CR_PAT }}

      
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK ${{ inputs.javaVersion }}
        run: echo "${{ inputs.javaVersion }}"    

      - name: Print repository_owner dispatch 
        run: echo "${{ github.event.inputs.ownerName }}"    
      - name: Print repository_owner ENV 
        run: echo "$OWNER_REPO"
      - name: Print repository_owner ENV 
        run: echo "${OWNER_REPO}"
#      - name: Print repository_owner ENV 
#        run: echo "${{ OWNER_REPO }}"
        
      - name: Print repository_owner
        run: echo "${{ github.repository_owner }}"
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'      
      
      
      
     
